### ISSUE TITLE
pyfrom import error

### ISSUE THREAD

**Issue by ccfuncy** [neonnnnn/pyrfm#6]
I tried your installation method of pyrfm and successfully installed pyrfm, but the following exception was thrown when I used it. Could you please provide me with help? Thank you

```
root@Ieb7bd1b1801501882:/pyrfm# python
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
from pyrfm import MB, SparseMBClassifier, SparseMB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyrfm/pyrfm/__init__.py", line 1, in <module>
    from .random_feature import (RandomFourier, RandomMaclaurin,
  File "/pyrfm/pyrfm/random_feature/__init__.py", line 2, in <module>
    from .random_kernel import RandomKernel, SubfeatureRandomKernel
  File "/pyrfm/pyrfm/random_feature/random_kernel.py", line 11, in <module>
    from ..kernels import anova, all_subsets, anova_fast, pairwise
  File "/pyrfm/pyrfm/kernels.py", line 4, in <module>
    from .kernels_fast import _anova, _all_subsets, _intersection, _chi_square
ModuleNotFoundError: No module named 'pyrfm.kernels_fast'
```

**Comment by neonnnnn** [comment]
@ccfuncy 
Sorry for my delayed response. It seems that you executed `python` command in the `/pyrfm` directory, so I think that the statement `from pyrfm import MB, SparseMBClassifier, SparseMB` tried to import your **local** `pyrfm`, namely, `/pyrfm/pyrfm`. Can you execute the same statement in a different directory?

**Comment by ccfuncy** [comment]
yes,so thank your response.I have solved this problem with a similar solution.
